# Generated by Django 3.2.3 on 2021-07-07 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_blog_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('desc', models.TextField(max_length=600)),
                ('image', models.ImageField(default='', upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='team',
            name='occupation',
            field=models.CharField(default='Marketing manager', max_length=100),
        ),
    ]
