# Generated by Django 3.2.3 on 2021-07-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20210707_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='occupation',
            field=models.CharField(default='Marketing manager', max_length=100),
        ),
    ]
